# Generated by Django 6.0.3 on 2026-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_patientinfo_alter_consultation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='specialization',
            field=models.CharField(choices=[('general', 'General Practice'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics')], default='general', max_length=20),
        ),
    ]
